# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
repos:
  CRAN: http://cran.rstudio.com
install:
  - ./travis-tool.sh github_package r-lib/covr
addons:
  apt:
    packages:
      - libxml2-dev
      - libv8-dev
warnings_are_errors: false
after_success: 
  - Rscript -e 'covr::coveralls()'
