# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 1.19
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
github_packages:
  - hadley/devtools
  - hadley/testthat
  - okgreece/datapackage.r
brew_packages:
 - jsonvalidate
 - sys
 - V8
r_packages:
 - brew
 - config
 - future
 - git2r
 - hash
 - httr
 - iterators
 - itertools2
 - jsonlite
 - lubridate
 - pdftools
 - purrr
 - R6
 - RCurl
 - Rcpp
 - readr
 - rlang
 - rlist
 - roxygen2
 - stringi
 - stringr
 - xml2
addons:
  apt:
    packages:
      - libxml2-dev
      - libv8-dev
      - libpoppler-cpp-dev
warnings_are_errors: false
